export const browserCoreExamples = [
  "jarvis browser status",
  "jarvis browser start",
  "jarvis browser stop",
  "jarvis browser tabs",
  "jarvis browser open https://example.com",
  "jarvis browser focus abcd1234",
  "jarvis browser close abcd1234",
  "jarvis browser screenshot",
  "jarvis browser screenshot --full-page",
  "jarvis browser screenshot --ref 12",
  "jarvis browser snapshot",
  "jarvis browser snapshot --format aria --limit 200",
  "jarvis browser snapshot --efficient",
  "jarvis browser snapshot --labels",
];

export const browserActionExamples = [
  "jarvis browser navigate https://example.com",
  "jarvis browser resize 1280 720",
  "jarvis browser click 12 --double",
  'jarvis browser type 23 "hello" --submit',
  "jarvis browser press Enter",
  "jarvis browser hover 44",
  "jarvis browser drag 10 11",
  "jarvis browser select 9 OptionA OptionB",
  "jarvis browser upload /tmp/jarvis/uploads/file.pdf",
  'jarvis browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "jarvis browser dialog --accept",
  'jarvis browser wait --text "Done"',
  "jarvis browser evaluate --fn '(el) => el.textContent' --ref 7",
  "jarvis browser console --level error",
  "jarvis browser pdf",
];
